### ISSUE TITLE
right-click is disabled on highlighted mods

### ISSUE THREAD

**Issue by Mehni** [DoctorVanGogh/ModSwitch#8]
Steps to repro:

1. Click on a mod to highlight it.
2. Right-click on it, to create a local copy or whatever.
3. Observe how, despite frantic clicking, no box pops up.

**Comment by DoctorVanGogh** [comment]
See [Steam Known Issues](http://steamcommunity.com/workshop/filedetails/discussion/1139051045/1496741765124594211/)...

Feel free to submit a PR 😉

**Comment by dawnmist** [comment]
May I suggest adding a note on the mod description on steam for this though?

It wasn't until I found this issue that I could work out why I wasn't getting the ability to change mod colors. I knew I'd done it before somehow (presumably after finding this issue the first time), but it took another 1/2 hour of hunting for why there wasn't a popup menu then coming across here to see if there were any reported issues or documentation for how to set colors.

A simple "Note: due to a known steam issue, the right-click menu for setting colors & creating local copies only works on unselected mods." on the steam mod page/mod description would be enough. :)

**Comment by DoctorVanGogh** [comment]
Yeah, fair point.... although it feels utterly redundant I've included the known issue(s) in the global description.
